## Numpy怎样给数组增加一个维度
#### 背景：
很多数据计算都是二维或三维的，对于一维的数据输入为了形状匹配，经常需升维变成二维
#### 需要：
在不改变数据的情况下，添加数组维度；（注意观察这个例子，维度变了，但数据不变）

原始数组：一维数组arr=[1,2,3,4]，其shape是（4，），取值分别为arr[0], arr[1], arr[2], arr[3]

变形数组：二维数组arr=[[1,2,3,4]]，其shape实（1,4），取值分别为a[0,0], a[0,1], a[0,2], a[0,3]
#### 实操：
经常需要在纸上手绘数组的形状，来查看不同数组是否形状匹配，是否需要升维降维
#### 3种方法：
* np.newaxis: 关键字，使用索引的语法给数组添加维度
* np.expand_dims(arr，axis）：方法，和np.newaxis实现一样的功能，给arr在axis位置添加维度
* np.reshape(a，newshape）：方法，给一个维度设置为1完成升维

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
# 注意，当前是一维向量
arr.shape

(5,)

### 方法1： np.newaxis关键字
注意：np.newaxis其实就是None的别名

In [4]:
np.newaxis is None

True

In [5]:
np.newaxis == None

True

即以下所有的np.newaxis，都可以用None代替

#### 给一维向量添加一个维度

In [6]:
arr[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [7]:
arr[np.newaxis, :].shape

(1, 5)

数据现在是一行 * 五列，数据本身没有增减，只是多了一级括号

#### 给一维向量添加一个列维度

In [8]:
arr[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [9]:
arr[:, np.newaxis].shape

(5, 1)

数据现在是五行 * 一列

### 方法2： np.expand_dims
np.expand_dims方法实现的效果，和np.newaxis关键字是一模一样的

In [10]:
arr

array([0, 1, 2, 3, 4])

#### 给一维数组添加一个行维度
相当于arr[np.newaxis, arr]

In [11]:
np.expand_dims(arr, axis=0)

array([[0, 1, 2, 3, 4]])

In [12]:
np.expand_dims(arr, axis=0).shape

(1, 5)

#### 给一维数组添加一个列维度
相当于arr[arr, np.newaxis]

In [13]:
np.expand_dims(arr, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [14]:
np.expand_dims(arr, axis=1).shape

(5, 1)

### 方法3：np.reshape方法

#### 给一维数组添加一个行维度

In [15]:
arr

array([0, 1, 2, 3, 4])

In [16]:
np.reshape(arr, (1, 5))

array([[0, 1, 2, 3, 4]])

In [18]:
np.reshape(arr, (1, -1))

array([[0, 1, 2, 3, 4]])

In [19]:
np.reshape(arr, (1, -1)).shape

(1, 5)

#### 给一维数组添加一个列维度

In [20]:
np.reshape(arr, (-1, 1))

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [21]:
np.reshape(arr, (-1, 1)).shape

(5, 1)