## Numpy的核心array对象以及创建array的方法
---

### array对象的背景：
* Numpy的核心数据结构，就叫做array就是数组，array对象可以是一维数组，也可以是多维数组；
* Python的List也可以实现相同的功能，但是array比List的优点在于性能好、包含数组元数据信息、大量的便捷函数；
* Numpy成为事实上的Scipy、Pandas、Scikit-Leam Tensorflow、PaddlePaddle等框架的“通用底层语言”
* Numpy的array和Python的List的一个区别，是它元素必须都是同一种数据类型，比如都是数字int类型，这也是Numpy高性能的一个原因；

### array本身的属性
* shape: 返回一个元组，表示array的维度
* ndim：一个数字，表示array的维度的数目
* size：一个数字，表示array中所有数据元素的数目
* dtype：array中元素的数据类型

### 创建array的方法
* 从Python的列表List和嵌套列表创建aray
* 使用预定函数arange、ones/ones_like、zeros/zeros_like、empty/empty_like、 full/full_like、eye等函数创建
* 生成随机数的np.random模块构建

### array本身支持的大量操作和函数
* 直接逐元素的加减乘除等算数操作
* 更好用的面向多维的数组索引
* 求sum/mean等聚合函数
* 线性代数函数，比如求解逆矩阵、求解方程组

## 1. 使用Python的List和嵌套List创建一维array和二维array

In [1]:
import numpy as np

In [2]:
# 创建一个一维数组，也就是Python的单元素List
x = np.array([1,2,3,4,5,6,7,8])

In [3]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
# 创建一个二维数组，也就是Python的嵌套List

In [5]:
X = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)

In [6]:
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 2. 探索数组的array属性

In [7]:
x.shape

(8,)

In [8]:
X.shape

(2, 4)

In [9]:
x.ndim

1

In [10]:
X.ndim

2

In [11]:
x.size

8

In [12]:
X.size

8

In [13]:
x.dtype

dtype('int64')

In [14]:
X.dtype

dtype('int64')

## 3. 创建array的便捷函数

### 使用arange创建数字序列
arange([start,] stop[, step,], dtype=None)

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

### 使用ones创建全都是1的数组
np.ones(shape, dtype=None, order='C')
shape: int or tuple of ints Shape of the new array, e.g., (2,3) or 2.

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 使用ones_like创建形状相同的数组
ones_like(a, dtype=float, order='C')

In [19]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones_like(X)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### 使用zeros创建全是0的数组
np.zeros(shape, dtype=None, order='C')

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 使用zeros_like创建形状相同的数组
np.zeros_like(a, dtype=None)

In [23]:
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros_like(X)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### 使用empty创建全都是0的数组
empty(shape, dtype=float, order='C')
注意：数据是未初始化的，里面的值可能是随机值，不要用

In [25]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.empty((2, 4))

array([[0.00000000e+000, 0.00000000e+000, 1.97626258e-323,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        5.60612834e-309]])

### 使用empty_like创建形状相同的数组
empty_like(prototype, dtype=None)

In [27]:
np.empty_like(x)

array([               0,                0,                4,
                      0,                0,                0,
                      0, 1134693008673121])

In [28]:
np.empty_like(X)

array([[               0,                0,                4,
                       0],
       [               0,                0,                0,
        1134693008607493]])

### 使用full创建指定的数组
np.full(shape, fill_value, dtype=None, order='C')

In [29]:
np.full(10, 666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [30]:
np.full((2,4), 333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

### 使用full_like创建形状相同的数组
np.full_like(a, fill_value, dtype=None)

In [31]:
np.full_like(x, 666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [32]:
np.full_like(X, 666)

array([[666, 666, 666, 666],
       [666, 666, 666, 666]])

### 使用random模块生成随机的数组
randn(d0, d1, ..., dn)

In [33]:
np.random.randn()

0.3289046506866467

In [34]:
np.random.randn(3)

array([-1.3298962 ,  0.05496773,  0.71120875])

In [35]:
np.random.randn(3, 2)

array([[ 2.59287838, -2.01420559],
       [-0.49501358,  0.36806293],
       [ 1.815392  ,  0.21253489]])

In [36]:
np.random.randn(3,2,4)

array([[[-1.5437276 ,  1.01708646,  1.24802207,  1.85729071],
        [-0.08796033, -0.60113766, -0.46009727, -0.81398234]],

       [[-0.58638124, -0.64527142, -1.88204987, -1.28490861],
        [-0.82174557, -1.13935332,  1.71492216,  0.00224388]],

       [[-0.4104594 , -0.03930026,  0.03016466,  0.41610144],
        [-1.85222345, -0.61420921,  0.01603632,  0.60793187]]])

## 4. array本身支持大量操作和函数
这些操作如果用Python实现需要写很多for循环，用numpy数组很容易

In [37]:
A = np.arange(10).reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
A.shape

(2, 5)

In [39]:
A + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
A * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [41]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [42]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [43]:
B = np.random.randn(2, 5)
B

array([[-0.47269437,  0.75844762,  0.69094086, -0.61637254, -1.25853538],
       [ 0.23999785,  1.20315105,  1.29920756, -0.29549767, -2.26944267]])

In [44]:
A + B

array([[-0.47269437,  1.75844762,  2.69094086,  2.38362746,  2.74146462],
       [ 5.23999785,  7.20315105,  8.29920756,  7.70450233,  6.73055733]])

In [45]:
A - B

array([[ 0.47269437,  0.24155238,  1.30905914,  3.61637254,  5.25853538],
       [ 4.76000215,  4.79684895,  5.70079244,  8.29549767, 11.26944267]])