### Numpy非常重要有用的数组合并操作
背景： 在给机器学习准备数据的过程中，经常需要进行不同来源的数据合并的操作。
两类场景：
1. 给已有的数据添加多行，比如增添一些样本数据进去；
2. 给已有的数据添加多列，比如增添一些特征进去；

以下操作均可以实现数组合并：
* np.concatenate(array_list，axis=0/1）：沿着指定axis进行数组的合并
* np.vstack或者np.row_stack(array_list）：垂直vertically、 按行rowwise进行数据合并
* np.hstack或者np.column_stack(array_list）：水平horizontally、 按列columnwise进行数据合并

In [1]:
import numpy as np

#### 1. 怎样给数据添加新的多行

In [7]:
a = np.arange(6).reshape(2,3)
b = np.random.randint(10, 20, size=(4, 3))

In [8]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b

array([[13, 14, 18],
       [11, 18, 12],
       [19, 17, 10],
       [12, 18, 12]])

In [10]:
# 方法1
np.concatenate([a, b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [13, 14, 18],
       [11, 18, 12],
       [19, 17, 10],
       [12, 18, 12]])

In [11]:
# 方法2
np.vstack([a, b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [13, 14, 18],
       [11, 18, 12],
       [19, 17, 10],
       [12, 18, 12]])

In [13]:
# 方法3
np.row_stack([a, b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [13, 14, 18],
       [11, 18, 12],
       [19, 17, 10],
       [12, 18, 12]])

#### 2. 怎样给数据添加新的多列

In [14]:
a = np.arange(12).reshape(3, 4)
b = np.random.randint(10, 20, size=(3, 2))

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
b

array([[17, 19],
       [15, 17],
       [17, 17]])

In [17]:
# 方法1
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3, 17, 19],
       [ 4,  5,  6,  7, 15, 17],
       [ 8,  9, 10, 11, 17, 17]])

In [18]:
# 方法2
np.hstack([a, b])

array([[ 0,  1,  2,  3, 17, 19],
       [ 4,  5,  6,  7, 15, 17],
       [ 8,  9, 10, 11, 17, 17]])

In [19]:
# 方法3
np.column_stack([a, b])

array([[ 0,  1,  2,  3, 17, 19],
       [ 4,  5,  6,  7, 15, 17],
       [ 8,  9, 10, 11, 17, 17]])